apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gateway.fullname" . }}-role-binding
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gateway.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gateway.fullname" . }}-role